name: Demo

on: [repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run demo 1
      if: github.event.action == 'demo_test'
      run: |
        echo "the test action is dispatched"
    - name: Run demo 2
      if: github.event.action == 'demo_test2'
      run: |
        echo "the test2 action is dispatched"
